### ISSUE TITLE
Readme.md examples wrong?

### ISSUE THREAD

**Issue by pendragon-andyh** [piroor/tiny-esm-test-runner#1]
Firstly, thanks for contributing this. I have been looking for a lightweight test harness for ESModules.

The Readme file contains a couple of examples that are like:
```
testSuccess.parameters = [
  ['AAA', 'aaa'],
  ['BBB', 'bbb']
];
export function testUpperCase([expected, data]) {
  is(expected, data.toUppwerCase());
}
```

Should ```testSuccess.parameters``` be ```testUpperCase.parameters``` in this case?

And should ```is(expected, data.toUppwerCase());``` be ```is(expected, data.toUpperCase());```?

Regards
Andy

**Comment by piroor** [comment]
Thanks! I've fixed those mistakes.
